stage('Docker Build') {
    steps {
        sh 'docker build -t devsecops-app .'
    }
}

stage('Deploy') {
    steps {
        sh 'docker rm -f devsecops-app || true'
        sh 'docker run -d -p 5000:5000 devsecops-app'
    }
}
